@echo off
setlocal enabledelayedexpansion
color 0B

echo.
echo  =============================================================
echo    ARGUS (Autonomous Real-time General Utility System)
echo    1-Click Interactive Setup Wizard
echo  =============================================================
echo.

:: 1. Check Python
echo [1/4] Checking Python environment...
python --version >nul 2>&1
if %ERRORLEVEL% NEQ 0 (
    echo [!] Python was not found in PATH. Please install Python 3.10+ from python.org
    pause
    exit /b 1
)
echo [OK] Python is ready.

:: 2. Check Node.js
echo [2/4] Checking Node.js environment...
node --version >nul 2>&1
if %ERRORLEVEL% NEQ 0 (
    echo [!] Node.js was not found in PATH. Please install Node.js 18+ from nodejs.org
    pause
    exit /b 1
)
echo [OK] Node.js is ready.

:: 3. Interactive Configuration
echo.
echo -------------------------------------------------------------
echo  Configure Your Personal AI Assistant
echo -------------------------------------------------------------
echo.

set /p OWNER_NAME="Enter your name (e.g. Yusuf): "
if "%OWNER_NAME%"=="" set OWNER_NAME=User

echo.
echo Choose your LLM Provider:
echo   [1] Free Groq (Llama 3.3 70B) — Fast & Free (console.groq.com)
echo   [2] OpenRouter (Claude 3.5 Sonnet, DeepSeek V3/R1, GPT-4o)
echo   [3] OpenAI (ChatGPT / GPT-4o-mini)
echo   [4] Custom OpenAI-compatible / Local Ollama
echo.
set /p PROVIDER_CHOICE="Select provider [1-4] (default: 1): "
if "%PROVIDER_CHOICE%"=="" set PROVIDER_CHOICE=1

if "%PROVIDER_CHOICE%"=="2" (
    set LLM_PROVIDER=openrouter
    set /p API_KEY="Enter your OpenRouter API Key (sk-or-v1-...): "
    set LLM_MODEL=anthropic/claude-3.5-sonnet
) else if "%PROVIDER_CHOICE%"=="3" (
    set LLM_PROVIDER=openai
    set /p API_KEY="Enter your OpenAI API Key (sk-proj-...): "
    set LLM_MODEL=gpt-4o-mini
) else if "%PROVIDER_CHOICE%"=="4" (
    set LLM_PROVIDER=custom
    set /p CUSTOM_URL="Enter Base URL (e.g. http://localhost:11434/v1): "
    set /p API_KEY="Enter API Key (or press enter for dummy): "
    if "%API_KEY%"=="" set API_KEY=dummy
    set /p LLM_MODEL="Enter Model Name (e.g. llama3.3 or deepseek-chat): "
) else (
    set LLM_PROVIDER=groq
    set /p API_KEY="Enter your Groq API Key (gsk_...): "
    set LLM_MODEL=llama-3.3-70b-versatile
)

set /p PHONE_NUMBER="Enter your WhatsApp Phone Number with Country Code (no +, no spaces, e.g. 919876543210): "
if "%PHONE_NUMBER%"=="" set PHONE_NUMBER=918088421593

:: Generate 32-byte secret
set ARGUS_SECRET=argus_secret_%RANDOM%_%RANDOM%_%RANDOM%

:: 4. Write backend/.env
echo [3/4] Writing backend/.env...
(
    echo # Auto-generated by ARGUS Setup Wizard
    echo LLM_PROVIDER=%LLM_PROVIDER%
    if "%LLM_PROVIDER%"=="openrouter" (
        echo OPENROUTER_API_KEY=%API_KEY%
        echo OPENROUTER_MODEL=%LLM_MODEL%
    ) else if "%LLM_PROVIDER%"=="openai" (
        echo OPENAI_API_KEY=%API_KEY%
        echo OPENAI_MODEL=%LLM_MODEL%
    ) else if "%LLM_PROVIDER%"=="custom" (
        echo LLM_BASE_URL=%CUSTOM_URL%
        echo LLM_API_KEY=%API_KEY%
        echo LLM_MODEL=%LLM_MODEL%
    ) else (
        echo GROQ_API_KEY=%API_KEY%
        echo GROQ_MODEL=%LLM_MODEL%
    )
    echo ARGUS_SECRET=%ARGUS_SECRET%
    echo ARGUS_HOST=127.0.0.1
    echo ARGUS_PORT=8000
    echo OWNER_NAME=%OWNER_NAME%
    echo OWNER_BIO=User
    echo OWNER_TONE=casual, friendly, concise, authentic WhatsApp texting style
) > backend\.env

:: Write bridge/.env
(
    echo # Auto-generated by ARGUS Setup Wizard
    echo MY_JID=%PHONE_NUMBER%@s.whatsapp.net
    echo AI_BRAIN_URL=http://127.0.0.1:8000
    echo ARGUS_SECRET=%ARGUS_SECRET%
    echo LISTEN_MODE=all
    echo SEND_DELAY_MS=1500
    echo DEDICATED_GROUP_NAME=ARGUS
    echo OWNER_NAME=%OWNER_NAME%
) > bridge\.env

:: 5. Install dependencies
echo [4/4] Installing dependencies & compiling TypeScript bridge...
cd /d %~dp0backend && pip install -r requirements.txt >nul 2>&1
cd /d %~dp0bridge && npm install >nul 2>&1 && npm run build >nul 2>&1

echo.
echo  =============================================================
echo    ARGUS Setup Complete!
echo  =============================================================
echo.
echo  To start ARGUS anytime:
echo    Double-click start.bat
echo.
pause
